Watching for file changes with StatReloader
"GET /admin/admin_interface/theme/add/ HTTP/1.1" 302 0
"GET /admin/login/?next=/admin/admin_interface/theme/add/ HTTP/1.1" 200 16851
"GET /static/debug_toolbar/css/toolbar.css HTTP/1.1" 200 16630
"GET /static/debug_toolbar/js/toolbar.js HTTP/1.1" 200 14601
"GET /static/admin/css/login.css HTTP/1.1" 304 0
"GET /static/debug_toolbar/css/print.css HTTP/1.1" 200 43
"GET /static/debug_toolbar/js/utils.js HTTP/1.1" 200 4742
"POST /admin/login/?next=/admin/admin_interface/theme/add/ HTTP/1.1" 302 0
Not Found: /admin/admin_interface/theme/add/
"GET /admin/admin_interface/theme/add/ HTTP/1.1" 404 18001
"GET /admin/login/?next=/admin/admin_interface/theme/add/ HTTP/1.1" 302 0
"GET /admin/ HTTP/1.1" 200 23958
Watching for file changes with StatReloader
Not Found: /
"GET /admin/ HTTP/1.1" 200 23958
"GET / HTTP/1.1" 404 15402
"GET /static/admin/css/base.css HTTP/1.1" 304 0
"GET /static/admin/css/dark_mode.css HTTP/1.1" 304 0
"GET /static/admin/css/nav_sidebar.css HTTP/1.1" 304 0
"GET /static/debug_toolbar/js/toolbar.js HTTP/1.1" 304 0
"GET /static/debug_toolbar/css/toolbar.css HTTP/1.1" 304 0
"GET /static/admin/css/dashboard.css HTTP/1.1" 304 0
"GET /static/admin/css/responsive.css HTTP/1.1" 304 0
"GET /static/debug_toolbar/css/print.css HTTP/1.1" 304 0
"GET /static/admin/js/nav_sidebar.js HTTP/1.1" 304 0
"GET /static/admin/js/theme.js HTTP/1.1" 304 0
"GET /static/debug_toolbar/js/utils.js HTTP/1.1" 304 0
"GET /static/admin/img/icon-addlink.svg HTTP/1.1" 304 0
"GET /static/admin/img/icon-changelink.svg HTTP/1.1" 304 0
Not Found: /favicon.ico
"GET /favicon.ico HTTP/1.1" 404 15428
Not Found: /favicon.ico
"GET /favicon.ico HTTP/1.1" 404 15428
"GET /admin/ HTTP/1.1" 200 23957
Not Found: /db
"GET /db HTTP/1.1" 404 15392
"GET /les6/db HTTP/1.1" 301 0
Internal Server Error: /les6/db/
Traceback (most recent call last):
  File "E:\Edu\Django\Seminar\DjangoProject\.venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "E:\Edu\Django\Seminar\DjangoProject\.venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\Edu\Django\Seminar\DjangoProject\myproject\sixapp\views.py", line 12, in total_in_db
    return render(request, 'sixapp/total_count.html', context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\Edu\Django\Seminar\DjangoProject\.venv\Lib\site-packages\django\shortcuts.py", line 25, in render
    content = loader.render_to_string(template_name, context, request, using=using)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\Edu\Django\Seminar\DjangoProject\.venv\Lib\site-packages\django\template\loader.py", line 61, in render_to_string
    template = get_template(template_name, using=using)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\Edu\Django\Seminar\DjangoProject\.venv\Lib\site-packages\django\template\loader.py", line 19, in get_template
    raise TemplateDoesNotExist(template_name, chain=chain)
django.template.exceptions.TemplateDoesNotExist: sixapp/total_count.html
"GET /les6/db/ HTTP/1.1" 500 100774
E:\Edu\Django\Seminar\DjangoProject\myproject\sixapp\views.py changed, reloading.
Watching for file changes with StatReloader
Internal Server Error: /les6/db/
Traceback (most recent call last):
  File "E:\Edu\Django\Seminar\DjangoProject\.venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "E:\Edu\Django\Seminar\DjangoProject\.venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\Edu\Django\Seminar\DjangoProject\myproject\sixapp\views.py", line 12, in total_in_db
    return render(request, 'sixapp/total_count.html', context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\Edu\Django\Seminar\DjangoProject\.venv\Lib\site-packages\django\shortcuts.py", line 25, in render
    content = loader.render_to_string(template_name, context, request, using=using)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\Edu\Django\Seminar\DjangoProject\.venv\Lib\site-packages\django\template\loader.py", line 61, in render_to_string
    template = get_template(template_name, using=using)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\Edu\Django\Seminar\DjangoProject\.venv\Lib\site-packages\django\template\loader.py", line 19, in get_template
    raise TemplateDoesNotExist(template_name, chain=chain)
django.template.exceptions.TemplateDoesNotExist: sixapp/total_count.html
"GET /les6/db/ HTTP/1.1" 500 100909
"GET /les6/db/ HTTP/1.1" 200 13641
"GET /__debug__/render_panel/?store_id=7cffbc13c28b47399ae2a22716c35c72&panel_id=SQLPanel HTTP/1.1" 200 4567
"GET /__debug__/render_panel/?store_id=7cffbc13c28b47399ae2a22716c35c72&panel_id=RequestPanel HTTP/1.1" 200 2069
"GET /les6/view/ HTTP/1.1" 200 13627
"GET /les6/template HTTP/1.1" 301 0
"GET /les6/template/ HTTP/1.1" 200 13607
E:\Edu\Django\Seminar\DjangoProject\myproject\myproject\settings.py changed, reloading.
Watching for file changes with StatReloader
E:\Edu\Django\Seminar\DjangoProject\myproject\myproject\settings.py changed, reloading.
Watching for file changes with StatReloader
E:\Edu\Django\Seminar\DjangoProject\myproject\myproject\settings.py changed, reloading.
Watching for file changes with StatReloader
E:\Edu\Django\Seminar\DjangoProject\myproject\myproject\settings.py changed, reloading.
Watching for file changes with StatReloader
E:\Edu\Django\Seminar\DjangoProject\myproject\myproject\settings.py changed, reloading.
Watching for file changes with StatReloader
E:\Edu\Django\Seminar\DjangoProject\myproject\myproject\settings.py changed, reloading.
Watching for file changes with StatReloader
E:\Edu\Django\Seminar\DjangoProject\myproject\myproject\settings.py changed, reloading.
Watching for file changes with StatReloader
Watching for file changes with StatReloader
E:\Edu\Django\Seminar\DjangoProject\myproject\myproject\settings.py changed, reloading.
Watching for file changes with StatReloader
E:\Edu\Django\Seminar\DjangoProject\myproject\myproject\settings.py changed, reloading.
Watching for file changes with StatReloader
E:\Edu\Django\Seminar\DjangoProject\myproject\myproject\settings.py changed, reloading.
Watching for file changes with StatReloader
"GET /sem1app1/ HTTP/1.1" 500 59
E:\Edu\Django\Seminar\DjangoProject\myproject\myproject\settings.py changed, reloading.
Watching for file changes with StatReloader
"GET /sem1app1/ HTTP/1.1" 500 59
"GET /sem1app1/coin_flip HTTP/1.1" 500 59
Watching for file changes with StatReloader
"GET /sem1app1/coin-flips HTTP/1.1" 500 59
E:\Edu\Django\Seminar\DjangoProject\myproject\myproject\settings.py changed, reloading.
Watching for file changes with StatReloader
"GET /sem1app1/coin-flips HTTP/1.1" 500 59
"GET /sem1app1/add_author HTTP/1.1" 500 59
"GET /seminar/add_author HTTP/1.1" 500 59
"GET /seminar/add-author HTTP/1.1" 500 59
Watching for file changes with StatReloader
Internal Server Error: /seminar/add-author
Traceback (most recent call last):
  File "E:\Edu\Django\Seminar\DjangoProject\.venv\Lib\site-packages\django\contrib\sessions\backends\base.py", line 187, in _get_session
    return self._session_cache
           ^^^^^^^^^^^^^^^^^^^
AttributeError: 'SessionStore' object has no attribute '_session_cache'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "E:\Edu\Django\Seminar\DjangoProject\.venv\Lib\site-packages\django\db\backends\utils.py", line 105, in _execute
    return self.cursor.execute(sql, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\Edu\Django\Seminar\DjangoProject\.venv\Lib\site-packages\django\db\backends\sqlite3\base.py", line 329, in execute
    return super().execute(query, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
sqlite3.OperationalError: no such table: django_session

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "E:\Edu\Django\Seminar\DjangoProject\.venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "E:\Edu\Django\Seminar\DjangoProject\.venv\Lib\site-packages\debug_toolbar\middleware.py", line 85, in __call__
    panel.generate_stats(request, response)
  File "E:\Edu\Django\Seminar\DjangoProject\.venv\Lib\site-packages\debug_toolbar\panels\request.py", line 64, in generate_stats
    (k, request.session.get(k)) for k in sorted(request.session.keys())
                                                ^^^^^^^^^^^^^^^^^^^^^^
  File "E:\Edu\Django\Seminar\DjangoProject\.venv\Lib\site-packages\django\contrib\sessions\backends\base.py", line 123, in keys
    return self._session.keys()
           ^^^^^^^^^^^^^
  File "E:\Edu\Django\Seminar\DjangoProject\.venv\Lib\site-packages\django\contrib\sessions\backends\base.py", line 192, in _get_session
    self._session_cache = self.load()
                          ^^^^^^^^^^^
  File "E:\Edu\Django\Seminar\DjangoProject\.venv\Lib\site-packages\django\contrib\sessions\backends\db.py", line 42, in load
    s = self._get_session_from_db()
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\Edu\Django\Seminar\DjangoProject\.venv\Lib\site-packages\django\contrib\sessions\backends\db.py", line 32, in _get_session_from_db
    return self.model.objects.get(
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\Edu\Django\Seminar\DjangoProject\.venv\Lib\site-packages\django\db\models\manager.py", line 87, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\Edu\Django\Seminar\DjangoProject\.venv\Lib\site-packages\django\db\models\query.py", line 645, in get
    num = len(clone)
          ^^^^^^^^^^
  File "E:\Edu\Django\Seminar\DjangoProject\.venv\Lib\site-packages\django\db\models\query.py", line 382, in __len__
    self._fetch_all()
  File "E:\Edu\Django\Seminar\DjangoProject\.venv\Lib\site-packages\django\db\models\query.py", line 1928, in _fetch_all
    self._result_cache = list(self._iterable_class(self))
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\Edu\Django\Seminar\DjangoProject\.venv\Lib\site-packages\django\db\models\query.py", line 91, in __iter__
    results = compiler.execute_sql(
              ^^^^^^^^^^^^^^^^^^^^^
  File "E:\Edu\Django\Seminar\DjangoProject\.venv\Lib\site-packages\django\db\models\sql\compiler.py", line 1562, in execute_sql
    cursor.execute(sql, params)
  File "E:\Edu\Django\Seminar\DjangoProject\.venv\Lib\site-packages\django\db\backends\utils.py", line 122, in execute
    return super().execute(sql, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\Edu\Django\Seminar\DjangoProject\.venv\Lib\site-packages\django\db\backends\utils.py", line 79, in execute
    return self._execute_with_wrappers(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\Edu\Django\Seminar\DjangoProject\.venv\Lib\site-packages\django\db\backends\utils.py", line 92, in _execute_with_wrappers
    return executor(sql, params, many, context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\Edu\Django\Seminar\DjangoProject\.venv\Lib\site-packages\django\db\backends\utils.py", line 100, in _execute
    with self.db.wrap_database_errors:
  File "E:\Edu\Django\Seminar\DjangoProject\.venv\Lib\site-packages\django\db\utils.py", line 91, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "E:\Edu\Django\Seminar\DjangoProject\.venv\Lib\site-packages\django\db\backends\utils.py", line 105, in _execute
    return self.cursor.execute(sql, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\Edu\Django\Seminar\DjangoProject\.venv\Lib\site-packages\django\db\backends\sqlite3\base.py", line 329, in execute
    return super().execute(query, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
django.db.utils.OperationalError: no such table: django_session
"GET /seminar/add-author HTTP/1.1" 500 161104
E:\Edu\Django\Seminar\DjangoProject\myproject\myproject\settings.py changed, reloading.
Watching for file changes with StatReloader
Session data corrupted
"GET /seminar/add-author HTTP/1.1" 301 0
Session data corrupted
Internal Server Error: /seminar/add-author/
Traceback (most recent call last):
  File "E:\Edu\Django\Seminar\DjangoProject\.venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "E:\Edu\Django\Seminar\DjangoProject\.venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\Edu\Django\Seminar\DjangoProject\myproject\sem1app1\views.py", line 93, in author_form
    return render(request, 'sem1app1/add_customer.html', context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\Edu\Django\Seminar\DjangoProject\.venv\Lib\site-packages\django\shortcuts.py", line 25, in render
    content = loader.render_to_string(template_name, context, request, using=using)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\Edu\Django\Seminar\DjangoProject\.venv\Lib\site-packages\django\template\loader.py", line 61, in render_to_string
    template = get_template(template_name, using=using)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\Edu\Django\Seminar\DjangoProject\.venv\Lib\site-packages\django\template\loader.py", line 19, in get_template
    raise TemplateDoesNotExist(template_name, chain=chain)
django.template.exceptions.TemplateDoesNotExist: sem1app1/add_customer.html
"GET /seminar/add-author/ HTTP/1.1" 500 110956
"GET /static/debug_toolbar/css/toolbar.css HTTP/1.1" 304 0
"GET /static/debug_toolbar/js/toolbar.js HTTP/1.1" 304 0
"GET /static/debug_toolbar/css/print.css HTTP/1.1" 304 0
"GET /static/debug_toolbar/js/utils.js HTTP/1.1" 304 0
E:\Edu\Django\Seminar\DjangoProject\myproject\sem1app1\views.py changed, reloading.
Watching for file changes with StatReloader
Session data corrupted
"GET /seminar/add-author/ HTTP/1.1" 200 16370
Session data corrupted
Not Found: /seminar/games/
"GET /seminar/games/ HTTP/1.1" 404 18132
Session data corrupted
"GET /seminar/pick-game/ HTTP/1.1" 200 14941
Session data corrupted
"POST /seminar/pick-game/ HTTP/1.1" 200 14662
E:\Edu\Django\Seminar\DjangoProject\myproject\myproject\settings.py changed, reloading.
Watching for file changes with StatReloader
E:\Edu\Django\Seminar\DjangoProject\myproject\myproject\urls.py changed, reloading.
Watching for file changes with StatReloader
E:\Edu\Django\Seminar\DjangoProject\myproject\myproject\urls.py changed, reloading.
Watching for file changes with StatReloader
E:\Edu\Django\Seminar\DjangoProject\myproject\sem1app1\urls.py changed, reloading.
Watching for file changes with StatReloader
E:\Edu\Django\Seminar\DjangoProject\myproject\sem1app1\urls.py changed, reloading.
Watching for file changes with StatReloader
Watching for file changes with StatReloader
E:\Edu\Django\Seminar\DjangoProject\myproject\fourthapp\views.py changed, reloading.
Watching for file changes with StatReloader
E:\Edu\Django\Seminar\DjangoProject\myproject\fourthapp\views.py changed, reloading.
Watching for file changes with StatReloader
